name: node test CI and deploy 

on: 
  push:
    branches:
      - master
  
  pull_request:
     branches:
      - master  
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: action/chekout@v3
      - name: Use Node.js
        uses: action/setup-node@v3
        with:
          node-version: 14 
      - run: npm install
      - run: npm test

      



        

