
name: node test CI and deploy 


on: 
  push:
    branches:
      - master
  
  pull_request:
     branches:
      - master  
env:
  SERVICE_NAME: julio0619/node-ci
      
jobs:
  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 12, 14 ]
    name: Node ${{ matrix.node }} sample

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14 
      - run: npm install
      - run: npm test
      
      
  build_dockerhub:
    name: Build application on dockerhub
    needs: [build_test]
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.SERVICE_NAME }}
   
 
  terraform:
    name: "Terraform"
    needs: [build_dockerhub]
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Workflow
        working-directory: do_terraform
        run: |
          terraform init
          terraform terraform plan
          terraform terraform apply -auto-approve
